version: '3.1'

services:
  app:
    build: .
    ports: 
      - 3000:3000
    environment:
      - REDIS_URL=redis://redis
    depends_on: 
      - db
      - redis
  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      DB_USERNAME: mongo
      DB_PASSWORD: mongo

  redis:
    image: redis
    ports:
      - 6379:6379 